name: Build CKAN + NetKAN

on:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      configuration:
        type: string
        default: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7'
      - name: Build ckan.exe and netkan.exe
        run: ./build --configuration=${{ inputs.configuration }}
      - name: Run tests
        run: xvfb-run ./build test+only --configuration=${{ inputs.configuration }} --where="Category!=FlakyNetwork"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.configuration }}-repack-unsigned
          path: _build/repack/
          retention-days: 7
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.configuration }}-out
          path: _build/out/
          retention-days: 1
